import "./globals.css";
import {
  Concert_One,
  Inter,
  Maven_Pro,
  Permanent_Marker,
  Shadows_Into_Light,
} from "next/font/google";
import Navigation from "@/components/Navigation/Navigation.js";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const maven = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-maven",
  weight: "400",
});

const shadows = Shadows_Into_Light({
  subsets: ["latin"],
  variable: "--font-shadows",
  weight: "400",
});

const marker = Permanent_Marker({
  subsets: ["latin"],
  variable: "--font-marker",
  weight: "400",
});

const concert = Concert_One({
  subsets: ["latin"],
  variable: "--font-concert",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${maven.variable} ${shadows.variable} ${marker.variable} ${concert.variable}`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        />
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
